package com.taoswork.tallycheck.authority.client;

import com.taoswork.tallycheck.authority.atom.ProtectionMode;

import java.util.Collection;

/**
 * Specified a resource instance, for its belonging IKProtection,
 * The instance could be included in a set of cases,
 * and also not included by the left cases
 *
 * Generated by
 *      INativeCoreProtectionCenter ({@link INativeCoreProtectionCenter})
 * Consumed by
 *      KAccessVerifier ({@link KAccessVerifier})
 */
public final class KCaseFitting {
    public final String resourceEntity;

    public final boolean isMasterControlled;
    public final ProtectionMode protectionMode;

    public final Collection<String> matching;
    public final Collection<String> unmatched;

    public KCaseFitting(String resourceEntity,
                        boolean isMasterControlled,
                        ProtectionMode protectionMode,
                        Collection<String> matching,
                        Collection<String> unmatched) {
        this.resourceEntity = resourceEntity;
        this.isMasterControlled = isMasterControlled;
        this.protectionMode = protectionMode;
        this.matching = matching;
        this.unmatched = unmatched;
    }
}
